config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "nails#index"
  resources :users
  resources :nails, only: %i(index new create show destroy) do
    # この行を追加する
    resources :likes, only: %i(create destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :nail

  validates :user_id, uniqueness: { scope: :nail_id }
end

app/models/nail.rb
class Nail < ApplicationRecord
  belongs_to :user
  attachment :image

  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end

  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy

  def liked_by(user)
    puts user.inspect, '11111'
    Like.find_by(user_id: user.id, nail_id: id)
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :nails, dependent: :destroy
  validates :username, presence: true
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  #サイン済のユーザーにのみアクセスを許可
  def create
    @like = current_user.likes.build(like_params)
    @nail = @like.nail
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like =Like.find_by(id: params[:id])
    @nail= @like.nail
    if @like.destroy
      respond_to :js
    end
  end

  private
  def like_params
    params.permit(:nail_id)
  end
end

app/controllers/nails_controller.rb
class NailsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @nails = Nail.all.order(id: "DESC")
  end

  def show
    @nail = Nail.find(params[:id])
  end

  def new
    @nail = Nail.new
  end

  def create
    @nail = Nail.new(nail_params)
    @nail.user_id = current_user.id
    if @nail.save
    # redirect_to nail_path(@nail)
      redirect_to user_path(@nail.user_id)
    else
      render :new
    end
  end

  def edit
    @nail = Nail.find(params[:id])
    if @nail.user != current_user
      redirect_to nails_path, alert: "不正なアクセスです"
    end
  end

  def update
    @nail = Nail.find(params[:id])
    if @nail.update(nail_params)
      redirect_to nail_path(@nail)
    else
      render :edit
    end
  end

  def destroy
    nail = Nail.find(params[:id])
    nail.destroy
    redirect_to nails_path
  end

  private
  def nail_params
    params.require(:nail).permit(:title, :body, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @sort_nails = @user.nails.all.order(id: "DESC")
    puts @sort_nails.inspect, '222222222222'
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー投稿を更新しました"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nailgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert]%>
      <div class="notification is-daner">
    <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">Naildesign</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "新規投稿", new_nail_path, class: "button is-warning is-light"%>
                </p>
                <p class="control">
                  <%= link_to "メッセージ", "#", class: "button is-warning is-light"%>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light"%>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light"%>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light"%>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light"%>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
$('#like-icon-nail-<%= @nail.id.to_s %>').
  html('<%= link_to "いいね", nail_like_path(@nail.id, @like), method: :DELETE, remote: true, class: "loved hide-text" %>');
$('#like-text-nail-<%= @nail.id.to_s %>').
  html('<%= j render "nails/like_text", { likes: @nail.likes } %>');

app/views/likes/destroy.js.erb
$('#like-icon-nail-<%= @nail.id.to_s %>').
  html('<%= link_to "いいねを取り消す", nail_likes_path(@nail), method: :nail, remote: true, class: "love hide-text" %>');
$('#like-text-nail-<%= @nail.id.to_s %>').
  html('<%= j render "nails/like_text", { likes: @nail.likes } %>');

app/views/nails/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.username %>  が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.username %> が「いいね！」しました
    <% elsif index > 1 %>
      <%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.username %>
    <% else %>
      <%= like.user.username + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/nails/edit.html.erb
<% if @nail.errors.any?%>
  <div class="notification is-danger">
    <h2><%= pluralize(@nail.errors.count, "error")%> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @nail.errors.full_messages.each do |message|%>
        <li><%= message%></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @nail do |f| %>

 <%= f.label :タイトル%>
 <%= f.text_field :title%>

 <%= f.label :テキスト%>
 <%= f.text_area :body%>

 <%= f.label :画像%>
 <%= f.attachment_field :image%>

  <%= f.submit "更新", class: "button is-danger is-light"%>

<% end %>

app/views/nails/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @nails.each do |nail| %>
        <div class="column is-4">
          <div class="card">
            <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag nail.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to nail.user.username, user_path(nail.user) %><%= nail.id %></div>
                </div>
            </div>

            <div id="like-icon-post-<%= nail.id.to_s %>">
              <% if nail.liked_by(current_user).present? %>

                <%= link_to nail_like_path(nail.id, nail.liked_by(current_user)), method: :delete do %>
              <i class="fas fa-heart"></i>
            <% end %>


              <% else %>
                <%= link_to "いいね", nail_likes_path(nail), method: :POST, remote: true, class: "fas fa-heart" %>
              <% end %>
            </div>

            <div id="like-text-post-<%= nail.id.to_s %>">
              <%= render "like_text", { likes: nail.likes } %>

          </div>



            <div class="card-content">
              <div class="card-image">
                <figure class="image is-4by3 image_size">
                  <%= link_to nail_path(nail) do %>
                    <%= attachment_image_tag nail, :image %>
                  <% end %>
                </figure>
              </div>
              <div class="content">
                <time><%= nail.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
              <%# https://techacademy.jp/magazine/30077 %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/nails/new.html.erb
<% if @nail.errors.any?%>
  <div class="notification is-danger">
    <h2><%= pluralize(@nail.errors.count, "error")%> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @nail.errors.full_messages.each do |message|%>
        <li><%= message%></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @nail do |f| %>

<%= f.label :タイトル%>
<%= f.text_field :title%>

<%= f.label :テキスト%>
<%= f.text_area :body%>

<%= f.label :画像%>
<%= f.attachment_field :image%>

<%= f.submit "投稿", class: "button is-danger is-light"%>

<% end %>

app/views/nails/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @nail, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @nail.title %></p>
                <div>
                aaaaaaa
                  <div id="like-icon-post-<%= @nail.id.to_s %>">
                    <% if @nail.liked_by(current_user).present? %>
                      <%= link_to "いいねを取り消す", nail_like_path(@nail.id, @nail.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
                    <% else %>
                      <%= link_to "いいね", nail_likes_path(@nail), method: :POST, remote: true, class: "love hide-text" %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <td><%= simple_format @nail.body%></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<% if @user.errors.any?%>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error")%> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message|%>
        <li><%= message%></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>

 <%= f.label :username%>
 <%= f.text_field :username%>

 <%= f.label :email%>
 <%= f.text_field :email%>

 <%= f.label :フリースペース%>
 <%= f.text_field :profile%>

 <%= f.label :プロフィール画像%>
 <%= f.attachment_field :profile_image%>

  <%= f.submit "更新", class: "button is-danger is-light"%>

<% end %>

app/views/users/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <%# 全件取得したユーザーの情報をeachで一つ一つ取り出して、userという変数に入れている %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.png"%>
                  <% end%>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user)%></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.nails.count%>
              </div>
            </div>
          </div>
        </div>
      <% end%>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128" style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image"%>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username%></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                <%=link_to "編集", edit_user_path(@user), class: "button is-primary"%>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <p>投稿数：<%= @user.nails.count%></p>
                </td>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile%>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @sort_nails.each do |nail| %>
        <div class="column is-4">
          <div class="card">
            <%if @user.id == current_user.id%>
              <div class="edit">
                <%= link_to "編集", edit_nail_path(nail)%>
              </div>
            <% end %>
            <div class="card-content">
              <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to nail_path(nail) do %>
                  <%= attachment_image_tag nail, :image %>
                <% end %>
              </figure>
            </div>
              <div class="content">
                <time><%= nail.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
              <%# https://techacademy.jp/magazine/30077 %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>



      <%# <%= link_to "詳細", nail_path(nail) %> 
      <%# <%= link_to "削除", nail_path(nail), method: :delete, data: {confirm: "削除しますか？"}%> 